version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:10.9.0
    environment:
        TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    steps:
      - run:
          name: Change Locale
          command: locale-gen en_US.UTF-8
      - checkout
      - run:
          name: Install Firebase CLI
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
